/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Info */
        get: operations["info_api_v1_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Threads */
        get: operations["threads_api_v1_threads_get"];
        put?: never;
        /** Create Thread */
        post: operations["create_thread_api_v1_threads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thread */
        get: operations["thread_api_v1_threads__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{thread_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_v1_threads__thread_id__runs_get"];
        put?: never;
        /** Start */
        post: operations["start_api_v1_threads__thread_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{thread_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run */
        get: operations["run_api_v1_threads__thread_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{thread_id}/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_threads__thread_id__runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{thread_id}/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_threads__thread_id__runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{thread_id}/runs/{run_id}/approvals/{call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_v1_threads__thread_id__runs__run_id__approvals__call_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalDecision */
        ApprovalDecision: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "allow" | "deny";
        };
        /** ApprovalEvent */
        ApprovalEvent: {
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /** Timestamp */
            timestamp: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "approval.required" | "approval.resolved";
            /** Call Id */
            call_id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
            /** Decision */
            decision?: ("allow" | "deny") | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Message */
        Message: {
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant" | "tool";
            /** Content */
            content: string;
            /** Name */
            name?: string | null;
            /** Tool Call Id */
            tool_call_id?: string | null;
            /** Id */
            id?: string;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCallRequest"][];
            /** Run Id */
            run_id?: string | null;
        };
        /** Run */
        Run: {
            /** Id */
            id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Status
             * @default running
             * @enum {string}
             */
            status: "running" | "waiting_approval" | "cancelling" | "succeeded" | "failed" | "cancelled" | "interrupted";
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Error */
            error?: string | null;
        };
        /** RunDetail */
        RunDetail: {
            run: components["schemas"]["Run"];
            /** Events */
            events: (components["schemas"]["TextEvent"] | components["schemas"]["ToolEvent"] | components["schemas"]["ApprovalEvent"] | components["schemas"]["StateEvent"])[];
        };
        /** SendMessage */
        SendMessage: {
            /** Text */
            text: string;
        };
        /** ServiceInfo */
        ServiceInfo: {
            /** Model */
            model: string;
            /** Configured */
            configured: boolean;
        };
        /** StateEvent */
        StateEvent: {
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /** Timestamp */
            timestamp: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.state";
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "waiting_approval" | "cancelling" | "succeeded" | "failed" | "cancelled" | "interrupted";
            /** Error */
            error?: string | null;
        };
        /** TextEvent */
        TextEvent: {
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /** Timestamp */
            timestamp: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message.delta";
            /** Message Id */
            message_id: string;
            /** Delta */
            delta: string;
        };
        /** ThreadDetail */
        ThreadDetail: {
            thread: components["schemas"]["ThreadSummary"];
            /** Messages */
            messages: components["schemas"]["Message"][];
            /** Tool Calls */
            tool_calls: components["schemas"]["ToolCallRecord"][];
            /** Todos */
            todos: components["schemas"]["TodoItem"][];
            active_run: components["schemas"]["Run"] | null;
        };
        /** ThreadSummary */
        ThreadSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /** TodoItem */
        TodoItem: {
            /** Id */
            id: string;
            /** Content */
            content: string;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "in_progress" | "completed";
            /** Created At */
            created_at?: string;
            /** Updated At */
            updated_at?: string;
        };
        /** ToolCallRecord */
        ToolCallRecord: {
            /** Call Id */
            call_id: string;
            /** Name */
            name: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /**
             * State
             * @enum {string}
             */
            state: "PENDING" | "APPROVAL_REQUIRED" | "APPROVED" | "EXECUTING" | "COMPLETED" | "FAILED" | "DENIED";
            /** Result */
            result?: unknown | null;
            /** Error */
            error?: string | null;
            /** Created At */
            created_at?: string;
            /** Updated At */
            updated_at?: string;
            /** Run Id */
            run_id?: string | null;
        };
        /** ToolCallRequest */
        ToolCallRequest: {
            /** Name */
            name: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
            /** Call Id */
            call_id?: string | null;
        };
        /** ToolEvent */
        ToolEvent: {
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /** Timestamp */
            timestamp: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool.completed" | "tool.failed" | "tool.started";
            /** Call Id */
            call_id: string;
            /** Name */
            name: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
            /** Result */
            result?: unknown;
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    info_api_v1_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceInfo"];
                };
            };
        };
    };
    threads_api_v1_threads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadSummary"][];
                };
            };
        };
    };
    create_thread_api_v1_threads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadSummary"];
                };
            };
        };
    };
    thread_api_v1_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_v1_threads__thread_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_v1_threads__thread_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessage"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_v1_threads__thread_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_threads__thread_id__runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "last-event-id"?: number | null;
            };
            path: {
                thread_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_threads__thread_id__runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_v1_threads__thread_id__runs__run_id__approvals__call_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
                run_id: string;
                call_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
