"""Store protocol used by the runtime."""

from collections.abc import AsyncIterator
from typing import Any, Protocol

from science_agent.types import AgentChannel, AgentEventEnvelope, AgentInfo, Message, ToolCallRecord


class Store(Protocol):
    async def save_messages(self, agent_id: str, messages: list[Message]) -> None: ...
    async def load_messages(self, agent_id: str) -> list[Message]: ...
    async def save_tool_call_records(
        self, agent_id: str, records: list[ToolCallRecord]
    ) -> None: ...
    async def load_tool_call_records(self, agent_id: str) -> list[ToolCallRecord]: ...
    async def append_event(
        self, agent_id: str, envelope: AgentEventEnvelope
    ) -> None: ...
    def read_events(
        self,
        agent_id: str,
        *,
        since: int | None = None,
        channel: AgentChannel | None = None,
    ) -> AsyncIterator[AgentEventEnvelope]: ...
    async def save_info(self, agent_id: str, info: AgentInfo) -> None: ...
    async def load_info(self, agent_id: str) -> AgentInfo | None: ...
    async def save_todos(self, agent_id: str, todos: list[dict]) -> None: ...
    async def load_todos(self, agent_id: str) -> list[dict]: ...
    async def save_snapshot(
        self, agent_id: str, snapshot_id: str, snapshot: dict[str, Any]
    ) -> None: ...
    async def load_snapshot(
        self, agent_id: str, snapshot_id: str
    ) -> dict[str, Any] | None: ...
    async def list_snapshots(self, agent_id: str) -> list[str]: ...
    async def list(self, prefix: str | None = None) -> list[str]: ...
    async def delete(self, agent_id: str) -> None: ...
