"""Store protocol used by the runtime."""

from typing import Protocol

from science_agent.types import AgentEventEnvelope, AgentInfo, Message, ToolCallRecord


class Store(Protocol):
    async def save_messages(self, agent_id: str, messages: list[Message]) -> None: ...
    async def load_messages(self, agent_id: str) -> list[Message]: ...
    async def save_tool_call_records(
        self, agent_id: str, records: list[ToolCallRecord]
    ) -> None: ...
    async def load_tool_call_records(self, agent_id: str) -> list[ToolCallRecord]: ...
    async def append_event(
        self, agent_id: str, envelope: AgentEventEnvelope
    ) -> None: ...
    async def save_info(self, agent_id: str, info: AgentInfo) -> None: ...
    async def load_info(self, agent_id: str) -> AgentInfo | None: ...
    async def save_todos(self, agent_id: str, todos: list[dict]) -> None: ...
    async def load_todos(self, agent_id: str) -> list[dict]: ...
